#datasource specific properties
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://mysqlcontainer:3306/ecomdb
#jpa properties

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

message: In Default Profile